name: deep_rl_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.16
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.4.127
  - cuda-runtime=12.1.0
  - filelock=3.14.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - ld_impl_linux-64=2.40
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=13.2.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4.20240210
  - networkx=3.3
  - openssl=3.3.0
  - pip=24.0
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.3.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - setuptools=69.5.1
  - sympy=1.12
  - tk=8.6.13
  - torchtriton=2.3.0
  - typing_extensions=4.11.0
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - box2d-py==2.3.5
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==4.4.2
      - farama-notifications==0.0.4
      - fonttools==4.51.0
      - grpcio==1.63.0
      - gymnasium==0.29.1
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - kiwisolver==1.4.5
      - markdown==3.6
      - matplotlib==3.8.4
      - moviepy==1.0.3
      - numpy==1.26.4
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - proglog==0.1.10
      - protobuf==5.26.1
      - pygame==2.5.2
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.31.0
      - six==1.16.0
      - swig==4.2.1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - torch-tb-profiler==0.4.3
      - tqdm==4.66.4
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.2
